// All countries



// length 252
type Country={
    code:string;
    code3:string;
    name:string;
    phone:string
}
export const countries:Country[] = [
{code: "AF", code3: "AFG", name: "Afghanistan", phone: "004"},
{code: "AL", code3: "ALB", name: "Albania", phone: "008"},
{code: "DZ", code3: "DZA", name: "Algeria", phone: "012"},
{code: "AS", code3: "ASM", name: "American Samoa", phone: "016"},
{code: "AD", code3: "AND", name: "Andorra", phone: "020"},
{code: "AO", code3: "AGO", name: "Angola", phone: "024"},
{code: "AI", code3: "AIA", name: "Anguilla", phone: "660"},
{code: "AQ", code3: "ATA", name: "Antarctica", phone: "010"},
{code: "AG", code3: "ATG", name: "Antigua and Barbuda", phone: "028"},
{code: "AR", code3: "ARG", name: "Argentina", phone: "032"},
{code: "AM", code3: "ARM", name: "Armenia", phone: "051"},
{code: "AW", code3: "ABW", name: "Aruba", phone: "533"},
{code: "AU", code3: "AUS", name: "Australia", phone: "036"},
{code: "AT", code3: "AUT", name: "Austria", phone: "040"},
{code: "AZ", code3: "AZE", name: "Azerbaijan", phone: "031"},
{code: "BS", code3: "BHS", name: "Bahamas (the)", phone: "044"},
{code: "BH", code3: "BHR", name: "Bahrain", phone: "048"},
{code: "BD", code3: "BGD", name: "Bangladesh", phone: "050"},
{code: "BB", code3: "BRB", name: "Barbados", phone: "052"},
{code: "BY", code3: "BLR", name: "Belarus", phone: "112"},
{code: "BE", code3: "BEL", name: "Belgium", phone: "056"},
{code: "BZ", code3: "BLZ", name: "Belize", phone: "084"},
{code: "BJ", code3: "BEN", name: "Benin", phone: "204"},
{code: "BM", code3: "BMU", name: "Bermuda", phone: "060"},
{code: "BT", code3: "BTN", name: "Bhutan", phone: "064"},
{code: "BO", code3: "BOL", name: "Bolivia (Plurinational State of)", phone: "068"},
{code: "BQ", code3: "BES", name: "Bonaire, Sint Eustatius and Saba", phone: "535"},
{code: "BA", code3: "BIH", name: "Bosnia and Herzegovina", phone: "070"},
{code: "BW", code3: "BWA", name: "Botswana", phone: "072"},
{code: "BV", code3: "BVT", name: "Bouvet Island", phone: "074"},
{code: "BR", code3: "BRA", name: "Brazil", phone: "076"},
{code: "IO", code3: "IOT", name: "British Indian Ocean Territory (the)", phone: "086"},
{code: "BN", code3: "BRN", name: "Brunei Darussalam", phone: "096"},
{code: "BG", code3: "BGR", name: "Bulgaria", phone: "100"},
{code: "BF", code3: "BFA", name: "Burkina Faso", phone: "854"},
{code: "BI", code3: "BDI", name: "Burundi", phone: "108"},
{code: "CV", code3: "CPV", name: "Cabo Verde", phone: "132"},
{code: "KH", code3: "KHM", name: "Cambodia", phone: "116"},
{code: "CM", code3: "CMR", name: "Cameroon", phone: "120"},
{code: "CA", code3: "CAN", name: "Canada", phone: "124"},
{code: "KY", code3: "CYM", name: "Cayman Islands (the)", phone: "136"},
{code: "CF", code3: "CAF", name: "Central African Republic (the)", phone: "140"},
{code: "TD", code3: "TCD", name: "Chad", phone: "148"},
{code: "CL", code3: "CHL", name: "Chile", phone: "152"},
{code: "CN", code3: "CHN", name: "China", phone: "156"},
{code: "CX", code3: "CXR", name: "Christmas Island", phone: "162"},
{code: "CC", code3: "CCK", name: "Cocos (Keeling) Islands (the)", phone: "166"},
{code: "CO", code3: "COL", name: "Colombia", phone: "170"},
{code: "KM", code3: "COM", name: "Comoros (the)", phone: "174"},
{code: "CD", code3: "COD", name: "Congo (the Democratic Republic of the)", phone: "180"},
{code: "CG", code3: "COG", name: "Congo (the)", phone: "178"},
{code: "CK", code3: "COK", name: "Cook Islands (the)", phone: "184"},
{code: "CR", code3: "CRI", name: "Costa Rica", phone: "188"},
{code: "HR", code3: "HRV", name: "Croatia", phone: "191"},
{code: "CU", code3: "CUB", name: "Cuba", phone: "192"},
{code: "CW", code3: "CUW", name: "Curaçao", phone: "531"},
{code: "CY", code3: "CYP", name: "Cyprus", phone: "196"},
{code: "CZ", code3: "CZE", name: "Czechia", phone: "203"},
{code: "CI", code3: "CIV", name: "Côte d'Ivoire", phone: "384"},
{code: "DK", code3: "DNK", name: "Denmark", phone: "208"},
{code: "DJ", code3: "DJI", name: "Djibouti", phone: "262"},
{code: "DM", code3: "DMA", name: "Dominica", phone: "212"},
{code: "DO", code3: "DOM", name: "Dominican Republic (the)", phone: "214"},
{code: "EC", code3: "ECU", name: "Ecuador", phone: "218"},
{code: "EG", code3: "EGY", name: "Egypt", phone: "818"},
{code: "SV", code3: "SLV", name: "El Salvador", phone: "222"},
{code: "GQ", code3: "GNQ", name: "Equatorial Guinea", phone: "226"},
{code: "ER", code3: "ERI", name: "Eritrea", phone: "232"},
{code: "EE", code3: "EST", name: "Estonia", phone: "233"},
{code: "SZ", code3: "SWZ", name: "Eswatini", phone: "748"},
{code: "ET", code3: "ETH", name: "Ethiopia", phone: "231"},
{code: "FK", code3: "FLK", name: "Falkland Islands (the) [Malvinas]", phone: "238"},
{code: "FO", code3: "FRO", name: "Faroe Islands (the)", phone: "234"},
{code: "FJ", code3: "FJI", name: "Fiji", phone: "242"},
{code: "FI", code3: "FIN", name: "Finland", phone: "246"},
{code: "FR", code3: "FRA", name: "France", phone: "250"},
{code: "GF", code3: "GUF", name: "French Guiana", phone: "254"},
{code: "PF", code3: "PYF", name: "French Polynesia", phone: "258"},
{code: "TF", code3: "ATF", name: "French Southern Territories (the)", phone: "260"},
{code: "GA", code3: "GAB", name: "Gabon", phone: "266"},
{code: "GM", code3: "GMB", name: "Gambia (the)", phone: "270"},
{code: "GE", code3: "GEO", name: "Georgia", phone: "268"},
{code: "DE", code3: "DEU", name: "Germany", phone: "276"},
{code: "GH", code3: "GHA", name: "Ghana", phone: "288"},
{code: "GI", code3: "GIB", name: "Gibraltar", phone: "292"},
{code: "GR", code3: "GRC", name: "Greece", phone: "300"},
{code: "GL", code3: "GRL", name: "Greenland", phone: "304"},
{code: "GD", code3: "GRD", name: "Grenada", phone: "308"},
{code: "GP", code3: "GLP", name: "Guadeloupe", phone: "312"},
{code: "GU", code3: "GUM", name: "Guam", phone: "316"},
{code: "GT", code3: "GTM", name: "Guatemala", phone: "320"},
{code: "GG", code3: "GGY", name: "Guernsey", phone: "831"},
{code: "GN", code3: "GIN", name: "Guinea", phone: "324"},
{code: "GW", code3: "GNB", name: "Guinea-Bissau", phone: "624"},
{code: "GY", code3: "GUY", name: "Guyana", phone: "328"},
{code: "HT", code3: "HTI", name: "Haiti", phone: "332"},
{code: "HM", code3: "HMD", name: "Heard Island and McDonald Islands", phone: "334"},
{code: "VA", code3: "VAT", name: "Holy See (the)", phone: "336"},
{code: "HN", code3: "HND", name: "Honduras", phone: "340"},
{code: "HK", code3: "HKG", name: "Hong Kong", phone: "344"},
{code: "HU", code3: "HUN", name: "Hungary", phone: "348"},
{code: "IS", code3: "ISL", name: "Iceland", phone: "352"},
{code: "IN", code3: "IND", name: "India", phone: "356"},
{code: "ID", code3: "IDN", name: "Indonesia", phone: "360"},
{code: "IR", code3: "IRN", name: "Iran (Islamic Republic of)", phone: "364"},
{code: "IQ", code3: "IRQ", name: "Iraq", phone: "368"},
{code: "IE", code3: "IRL", name: "Ireland", phone: "372"},
{code: "IM", code3: "IMN", name: "Isle of Man", phone: "833"},
{code: "IL", code3: "ISR", name: "Israel", phone: "376"},
{code: "IT", code3: "ITA", name: "Italy", phone: "380"},
{code: "JM", code3: "JAM", name: "Jamaica", phone: "388"},
{code: "JP", code3: "JPN", name: "Japan", phone: "392"},
{code: "JE", code3: "JEY", name: "Jersey", phone: "832"},
{code: "JO", code3: "JOR", name: "Jordan", phone: "400"},
{code: "KZ", code3: "KAZ", name: "Kazakhstan", phone: "398"},
{code: "KE", code3: "KEN", name: "Kenya", phone: "404"},
{code: "KI", code3: "KIR", name: "Kiribati", phone: "296"},
{code: "KP", code3: "PRK", name: "Korea (the Democratic People's Republic of)", phone: "408"},
{code: "KR", code3: "KOR", name: "Korea (the Republic of)", phone: "410"},
{code: "KW", code3: "KWT", name: "Kuwait", phone: "414"},
{code: "KG", code3: "KGZ", name: "Kyrgyzstan", phone: "417"},
{code: "LA", code3: "LAO", name: "Lao People's Democratic Republic (the)", phone: "418"},
{code: "LV", code3: "LVA", name: "Latvia", phone: "428"},
{code: "LB", code3: "LBN", name: "Lebanon", phone: "422"},
{code: "LS", code3: "LSO", name: "Lesotho", phone: "426"},
{code: "LR", code3: "LBR", name: "Liberia", phone: "430"},
{code: "LY", code3: "LBY", name: "Libya", phone: "434"},
{code: "LI", code3: "LIE", name: "Liechtenstein", phone: "438"},
{code: "LT", code3: "LTU", name: "Lithuania", phone: "440"},
{code: "LU", code3: "LUX", name: "Luxembourg", phone: "442"},
{code: "MO", code3: "MAC", name: "Macao", phone: "446"},
{code: "MG", code3: "MDG", name: "Madagascar", phone: "450"},
{code: "MW", code3: "MWI", name: "Malawi", phone: "454"},
{code: "MY", code3: "MYS", name: "Malaysia", phone: "458"},
{code: "MV", code3: "MDV", name: "Maldives", phone: "462"},
{code: "ML", code3: "MLI", name: "Mali", phone: "466"},
{code: "MT", code3: "MLT", name: "Malta", phone: "470"},
{code: "MH", code3: "MHL", name: "Marshall Islands (the)", phone: "584"},
{code: "MQ", code3: "MTQ", name: "Martinique", phone: "474"},
{code: "MR", code3: "MRT", name: "Mauritania", phone: "478"},
{code: "MU", code3: "MUS", name: "Mauritius", phone: "480"},
{code: "YT", code3: "MYT", name: "Mayotte", phone: "175"},
{code: "MX", code3: "MEX", name: "Mexico", phone: "484"},
{code: "FM", code3: "FSM", name: "Micronesia (Federated States of)", phone: "583"},
{code: "MD", code3: "MDA", name: "Moldova (the Republic of)", phone: "498"},
{code: "MC", code3: "MCO", name: "Monaco", phone: "492"},
{code: "MN", code3: "MNG", name: "Mongolia", phone: "496"},
{code: "ME", code3: "MNE", name: "Montenegro", phone: "499"},
{code: "MS", code3: "MSR", name: "Montserrat", phone: "500"},
{code: "MA", code3: "MAR", name: "Morocco", phone: "504"},
{code: "MZ", code3: "MOZ", name: "Mozambique", phone: "508"},
{code: "MM", code3: "MMR", name: "Myanmar", phone: "104"},
{code: "NA", code3: "NAM", name: "Namibia", phone: "516"},
{code: "NR", code3: "NRU", name: "Nauru", phone: "520"},
{code: "NP", code3: "NPL", name: "Nepal", phone: "524"},
{code: "NL", code3: "NLD", name: "Netherlands (the)", phone: "528"},
{code: "NC", code3: "NCL", name: "New Caledonia", phone: "540"},
{code: "NZ", code3: "NZL", name: "New Zealand", phone: "554"},
{code: "NI", code3: "NIC", name: "Nicaragua", phone: "558"},
{code: "NE", code3: "NER", name: "Niger (the)", phone: "562"},
{code: "NG", code3: "NGA", name: "Nigeria", phone: "566"},
{code: "NU", code3: "NIU", name: "Niue", phone: "570"},
{code: "NF", code3: "NFK", name: "Norfolk Island", phone: "574"},
{code: "MP", code3: "MNP", name: "Northern Mariana Islands (the)", phone: "580"},
{code: "NO", code3: "NOR", name: "Norway", phone: "578"},
{code: "OM", code3: "OMN", name: "Oman", phone: "512"},
{code: "PK", code3: "PAK", name: "Pakistan", phone: "586"},
{code: "PW", code3: "PLW", name: "Palau", phone: "585"},
{code: "PS", code3: "PSE", name: "Palestine, State of", phone: "275"},
{code: "PA", code3: "PAN", name: "Panama", phone: "591"},
{code: "PG", code3: "PNG", name: "Papua New Guinea", phone: "598"},
{code: "PY", code3: "PRY", name: "Paraguay", phone: "600"},
{code: "PE", code3: "PER", name: "Peru", phone: "604"},
{code: "PH", code3: "PHL", name: "Philippines (the)", phone: "608"},
{code: "PN", code3: "PCN", name: "Pitcairn", phone: "612"},
{code: "PL", code3: "POL", name: "Poland", phone: "616"},
{code: "PT", code3: "PRT", name: "Portugal", phone: "620"},
{code: "PR", code3: "PRI", name: "Puerto Rico", phone: "630"},
{code: "QA", code3: "QAT", name: "Qatar", phone: "634"},
{code: "MK", code3: "MKD", name: "Republic of North Macedonia", phone: "807"},
{code: "RO", code3: "ROU", name: "Romania", phone: "642"},
{code: "RU", code3: "RUS", name: "Russian Federation (the)", phone: "643"},
{code: "RW", code3: "RWA", name: "Rwanda", phone: "646"},
{code: "RE", code3: "REU", name: "Réunion", phone: "638"},
{code: "BL", code3: "BLM", name: "Saint Barthélemy", phone: "652"},
{code: "SH", code3: "SHN", name: "Saint Helena, Ascension and Tristan da Cunha", phone: "654"},
{code: "KN", code3: "KNA", name: "Saint Kitts and Nevis", phone: "659"},
{code: "LC", code3: "LCA", name: "Saint Lucia", phone: "662"},
{code: "MF", code3: "MAF", name: "Saint Martin (French part)", phone: "663"},
{code: "PM", code3: "SPM", name: "Saint Pierre and Miquelon", phone: "666"},
{code: "VC", code3: "VCT", name: "Saint Vincent and the Grenadines", phone: "670"},
{code: "WS", code3: "WSM", name: "Samoa", phone: "882"},
{code: "SM", code3: "SMR", name: "San Marino", phone: "674"},
{code: "ST", code3: "STP", name: "Sao Tome and Principe", phone: "678"},
{code: "SA", code3: "SAU", name: "Saudi Arabia", phone: "682"},
{code: "SN", code3: "SEN", name: "Senegal", phone: "686"},
{code: "RS", code3: "SRB", name: "Serbia", phone: "688"},
{code: "SC", code3: "SYC", name: "Seychelles", phone: "690"},
{code: "SL", code3: "SLE", name: "Sierra Leone", phone: "694"},
{code: "SG", code3: "SGP", name: "Singapore", phone: "702"},
{code: "SX", code3: "SXM", name: "Sint Maarten (Dutch part)", phone: "534"},
{code: "SK", code3: "SVK", name: "Slovakia", phone: "703"},
{code: "SI", code3: "SVN", name: "Slovenia", phone: "705"},
{code: "SB", code3: "SLB", name: "Solomon Islands", phone: "090"},
{code: "SO", code3: "SOM", name: "Somalia", phone: "706"},
{code: "ZA", code3: "ZAF", name: "South Africa", phone: "710"},
{code: "GS", code3: "SGS", name: "South Georgia and the South Sandwich Islands", phone: "239"},
{code: "SS", code3: "SSD", name: "South Sudan", phone: "728"},
{code: "ES", code3: "ESP", name: "Spain", phone: "724"},
{code: "LK", code3: "LKA", name: "Sri Lanka", phone: "144"},
{code: "SD", code3: "SDN", name: "Sudan (the)", phone: "729"},
{code: "SR", code3: "SUR", name: "Suriname", phone: "740"},
{code: "SJ", code3: "SJM", name: "Svalbard and Jan Mayen", phone: "744"},
{code: "SE", code3: "SWE", name: "Sweden", phone: "752"},
{code: "CH", code3: "CHE", name: "Switzerland", phone: "756"},
{code: "SY", code3: "SYR", name: "Syrian Arab Republic", phone: "760"},
{code: "TW", code3: "TWN", name: "Taiwan", phone: "158"},
{code: "TJ", code3: "TJK", name: "Tajikistan", phone: "762"},
{code: "TZ", code3: "TZA", name: "Tanzania, United Republic of", phone: "834"},
{code: "TH", code3: "THA", name: "Thailand", phone: "764"},
{code: "TL", code3: "TLS", name: "Timor-Leste", phone: "626"},
{code: "TG", code3: "TGO", name: "Togo", phone: "768"},
{code: "TK", code3: "TKL", name: "Tokelau", phone: "772"},
{code: "TO", code3: "TON", name: "Tonga", phone: "776"},
{code: "TT", code3: "TTO", name: "Trinidad and Tobago", phone: "780"},
{code: "TN", code3: "TUN", name: "Tunisia", phone: "788"},
{code: "TR", code3: "TUR", name: "Turkey", phone: "792"},
{code: "TM", code3: "TKM", name: "Turkmenistan", phone: "795"},
{code: "TC", code3: "TCA", name: "Turks and Caicos Islands (the)", phone: "796"},
{code: "TV", code3: "TUV", name: "Tuvalu", phone: "798"},
{code: "UG", code3: "UGA", name: "Uganda", phone: "800"},
{code: "UA", code3: "UKR", name: "Ukraine", phone: "804"},
{code: "AE", code3: "ARE", name: "United Arab Emirates (the)", phone: "784"},
{code: "GB", code3: "GBR", name: "United Kingdom of Great Britain and Northern Ireland (the)", phone: "826"},
{code: "UM", code3: "UMI", name: "United States Minor Outlying Islands (the)", phone: "581"},
{code: "US", code3: "USA", name: "United States of America (the)", phone: "840"},
{code: "UY", code3: "URY", name: "Uruguay", phone: "858"},
{code: "UZ", code3: "UZB", name: "Uzbekistan", phone: "860"},
{code: "VU", code3: "VUT", name: "Vanuatu", phone: "548"},
{code: "VE", code3: "VEN", name: "Venezuela (Bolivarian Republic of)", phone: "862"},
{code: "VN", code3: "VNM", name: "Viet Nam", phone: "704"},
{code: "VG", code3: "VGB", name: "Virgin Islands (British)", phone: "092"},
{code: "VI", code3: "VIR", name: "Virgin Islands (U.S.)", phone: "850"},
{code: "WF", code3: "WLF", name: "Wallis and Futuna", phone: "876"},
{code: "EH", code3: "ESH", name: "Western Sahara", phone: "732"},
{code: "YE", code3: "YEM", name: "Yemen", phone: "887"},
{code: "ZM", code3: "ZMB", name: "Zambia", phone: "894"},
{code: "ZW", code3: "ZWE", name: "Zimbabwe", phone: "716"},
{code: "AX", code3: "ALA", name: "Åland Islands", phone: "248"}
];